INSERT INTO ingredients (ingredient_name, stock_remaining)
VALUES
    ("Cheese", 50)
    ("Lactose free Cheese", 50)
    ("Pepperoni", 50)
    ("Bacon", 50)
    ("Sausage", 50)
    ("Pineapple", 50)
    ("Red Onion", 50)
    ("Green Pepper", 50)